### ISSUE TITLE
Too many colons in address.

### ISSUE THREAD

**Issue by cromulus** [lmars/flynn-webhook-deploy#6]
New flynn cluster, getting this error:
`[2016-08-11T20:56:25.593651708Z] 20:56:25.593519 postgres.go:54: Get http://192.168.200.11:1111,192.168.200.12:1111,192.168.200.13:1111/services/postgres: dial tcp: too many colons in address 192.168.200.11:1111,192.168.200.12:1111,192.168.200.13:1111`

**Comment by lmars** [comment]
@cromulus where are you seeing this error?

**Comment by cromulus** [comment]
In the Flynn dashboard logs for the web process. It crashes repeatedly.

I'll get you more detailed logs tomorrow.

Thanks!

**Comment by cromulus** [comment]
@lmars This is from the logs on the flynn dashboard.

**Comment by lmars** [comment]
@cromulus this doesn't seem to be anything to do with the `flynn-webhook-deploy` code, you should open an issue on the [Flynn repo](https://github.com/flynn/flynn), and also run `sudo flynn-host collect-debug-info` and include the resulting gist in your issue.

**Comment by cromulus** [comment]
Thanks!
