### ISSUE TITLE
Deploy Key for Private Repositories

### ISSUE THREAD

**Issue by skyebook** [lmars/flynn-webhook-deploy#7]
I have a feeling my private repository isn't deploying due to lack of access to the repo from the flynn host, is there a way to include a deploy key in the app config?

log for the flynn webhook-deploy app
```
Cloning into '/tmp/app'...
fatal: could not read Username for 'https://github.com': No such device or address
exit status 128
unexpected exit status: 1
```

**Comment by lmars** [comment]
@skyebook you should add your SSH key to the `taffy` app in Flynn (basically follow [these instructions](https://flynn.io/docs/production#ssh-client-key) but replace `gitreceive` with `taffy`):

```
flynn -a taffy env set SSH_CLIENT_HOSTS="$(ssh-keyscan -H github.com)" SSH_CLIENT_KEY="$(cat ~/.ssh/id_rsa)"
```
